language: python
dist: xenial
sudo: false
before_install:
    - wget https://gitlab.matrix.org/matrix-org/olm/-/archive/master/olm-master.tar.bz2
    - tar -xvf olm-master.tar.bz2
    - pushd olm-master && make && sudo make PREFIX="/usr" install && popd
    - rm -r olm-master

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - python: 3.7
          env: TOXENV=coverage
        - python: 3.8
          env: TOXENV=mypy


install: pip install tox-travis
script: tox

after_success:
    - bash <(curl -s https://codecov.io/bash)
